pages.learn = {
    categories: [
        {
            name: 'Bagian 1: Fondasi & Antarmuka',
            items: [
                {
                    id: 'modul01',
                    title: 'Pertemuan 1: Pengenalan Ekosistem Web',
                    lines: [
                        '**Pertemuan 1: Pengenalan Ekosistem Web & Kontrak Perkuliahan**',
                        '*Sebelum menulis satu baris kode pun, pahami dulu medan perangnya.*',
                        '---',
                        'Mahasiswa memahami aturan main, sistem penilaian, dan cakupan materi selama satu semester ke depan.',
                        'Fokus pada pemahaman arsitektur web modern dan roadmap pembangunan aplikasi CRUD fungsional.',
                        '---',
                        '### Kenapa Harus Paham Ekosistem Dulu?',
                        'card:Tanpa Peta, Anda Akan Tersesat:Developer yang langsung coding tanpa memahami arsitektur web sering membangun sesuatu yang \'bekerja di mesin sendiri\' tapi gagal di produksi. Peta ekosistem mencegah ini.',
                        'card:Satu Semester, Satu Aplikasi Nyata:Setiap pertemuan adalah satu potongan puzzle. Di akhir semester, potongan itu menyatu menjadi aplikasi CMS yang bisa Anda tunjukkan di portofolio dan wawancara kerja.',
                        'card:Vanilla JS — Pilihan yang Disengaja:Belajar tanpa framework adalah belajar cara berpikir. Setelah menguasai vanilla JS, belajar React atau Vue hanya butuh beberapa hari — karena Anda sudah paham fondasinya.',
                        '---',
                        '### Client-Side vs Server-Side — Peta Medan',
                        'table:[{"Aspek": "Lokasi Eksekusi", "Client-Side": "Di browser pengguna (HTML, CSS, JS)", "Server-Side": "Di server (Node.js, PHP, Python)"}, {"Aspek": "Penyimpanan Data", "Client-Side": "LocalStorage, IndexedDB, Cookie", "Server-Side": "Database terpusat (MySQL, PostgreSQL)"}, {"Aspek": "Kecepatan Respons", "Client-Side": "Sangat cepat — tidak butuh round-trip ke server", "Server-Side": "Tergantung jaringan dan beban server"}, {"Aspek": "Skala Data", "Client-Side": "Ideal untuk data ringan (< 5MB per user)", "Server-Side": "Tidak terbatas, data tersentralisasi"}, {"Aspek": "Fokus Semester Ini", "Client-Side": "✅ Fokus utama mata kuliah ini", "Server-Side": "Akan dipelajari di mata kuliah lanjutan"}]',
                        '---',
                        '### Konsep Dasar & Arsitektur',
                        'card:Client-Side:Kode berjalan di browser: HTML membangun struktur, CSS mengatur tampilan, JS memberikan logika dan interaktivitas.',
                        'card:Server-Side:Kode di server menangani logika bisnis, autentikasi, dan penyimpanan database terpusat. Semester ini kita tidak ke sini.',
                        'card:Data Flow via JSON:Pertukaran data antara komponen menggunakan format JSON — ringan, mudah dibaca manusia, dan dipahami semua bahasa pemrograman.',
                        '---',
                        '### Anatomi Proyek Web Sederhana',
                        '```javascript',

                        'code:bash:nord:false:# Struktur folder proyek semester ini\narticle-system/\n├── index.html        # Antarmuka utama (Pertemuan 2)\n├── style.css         # Tampilan & layout (Pertemuan 3-4)\n├── app.js            # Logika CRUD utama (Pertemuan 5-13)\n├── data.json         # Data awal via Fetch API (Pertemuan 11)\n└── assets/\n    ├── logo.png\n    └── favicon.ico\n\n# Tiga file inti (index.html + style.css + app.js)\n# adalah 100% dari yang dibutuhkan untuk UTS\n# Dua file tambahan (data.json + assets) untuk UAS',
                        '```',
                        '---',
                        '### Development Environment Setup',
                        'skill:100%:VS Code — Editor Utama:Wajib Install',
                        'skill:100%:Chrome/Edge + DevTools:Wajib — F12 adalah teman terbaik Anda',
                        'skill:100%:Live Server Extension (VS Code):Wajib — auto-reload saat coding',
                        'skill:50%:Git & GitHub:Sangat Dianjurkan untuk portofolio',
                        '---',
                        '### Ringkasan Aktivitas Pertemuan 1',
                        'table:[{"Aktivitas": "Penyampaian RPS", "Deskripsi": "Visi, misi, sistem penilaian, dan roadmap 16 pertemuan.", "Durasi": "30 Menit"}, {"Aktivitas": "Kuliah Teori", "Deskripsi": "Sejarah web, protokol HTTP, evolusi JavaScript, dan demo aplikasi target akhir semester.", "Durasi": "40 Menit"}, {"Aktivitas": "Praktikum Setup", "Deskripsi": "Instalasi VS Code + ekstensi, setup folder proyek, dan eksplorasi DevTools (Console, Network, Application tab).", "Durasi": "30 Menit"}, {"Aktivitas": "Diskusi", "Deskripsi": "Tanya jawab kontrak perkuliahan, ekspektasi proyek, dan pembentukan grup belajar.", "Durasi": "20 Menit"}]',
                        '---'
                    ]
                },
                {
                    id: 'modul02',
                    title: 'Pertemuan 2: HTML5 — Struktur & Semantik',
                    lines: [
                        '**Pertemuan 2: HTML5 — Struktur Data & Semantik Antarmuka**',
                        '*HTML bukan sekadar tag — ia adalah kontrak antara konten, browser, dan JavaScript.*',
                        '---',
                        'Fokus pada HTML5 sebagai penyedia input dan wadah render data untuk sistem LocalStorage.',
                        'Mahasiswa mempelajari anatomi dokumen, elemen semantik, dan optimasi form — karena ID yang salah di sini akan merusak seluruh logika JavaScript nanti.',
                        '---',
                        '### Mengapa Struktur HTML yang Benar Itu Krusial?',
                        'card:ID Salah = JS Buta:JavaScript mengambil elemen via ID. Jika ID typo atau tidak konsisten, document.getElementById() mengembalikan null dan seluruh logika CRUD berhenti berfungsi.',
                        'card:Semantik = SEO + Aksesibilitas:Tag <main>, <header>, <section> bukan sekadar estetika. Mereka membantu screen reader, mesin pencari, dan developer lain memahami struktur halaman tanpa membaca setiap baris.',
                        'card:Tabel Kosong = Canvas JavaScript:Kita sengaja membuat <tbody id=\'tableBody\'> yang kosong. JavaScript-lah yang akan mengisinya nanti — HTML hanya menyiapkan wadahnya.',
                        '---',
                        '### Boilerplate HTML5 — Struktur Wajib Proyek',
                        '```javascript',

                        'code:html:dracula:true:<!DOCTYPE html>\n<html lang="id">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Niura — Article System</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n\n  <header>\n    <h1>Niura</h1>\n  </header>\n\n  <main>\n    <!-- Form Input (Create) -->\n    <section id="form-section">\n      <form id="articleForm">\n        <input type="text"     id="inputTitle"   placeholder="Judul artikel...">\n        <textarea             id="inputContent" placeholder="Konten artikel..."></textarea>\n        <button type="submit" id="btnSave">Simpan</button>\n      </form>\n    </section>\n\n    <!-- Data Display (Read) -->\n    <section id="table-section">\n      <table>\n        <thead>\n          <tr><th>No</th><th>Judul</th><th>Konten</th><th>Aksi</th></tr>\n        </thead>\n        <tbody id="tableBody">\n          <!-- JavaScript akan mengisi bagian ini -->\n        </tbody>\n      </table>\n    </section>\n  </main>\n\n  <script src="app.js"></script> <!-- Selalu di bawah body -->\n</body>\n</html>',
                        '```',
                        '---',
                        '### 3 Komponen HTML Utama Aplikasi CRUD',
                        'card:Semantik Layout:Gunakan <header>, <main>, <section> untuk hierarki konten. Ini memudahkan CSS menargetkan area yang tepat dan developer lain memahami struktur.',
                        'card:Formulir Input:Jantung operasi Create & Update. Setiap elemen input HARUS memiliki id unik yang konsisten dengan variabel JS — ini kontrak yang tidak boleh dilanggar.',
                        'card:Data Display (tbody):Tag <tbody id=\'tableBody\'> adalah zona render JavaScript. Kosongkan di HTML, biarkan JS yang mengisi setiap baris secara dinamis.',
                        '---',
                        '### Contoh: Elemen ID yang Konsisten untuk CRUD',
                        '```javascript',

                        'code:html:nord:true:<!-- ❌ SALAH — ID tidak konsisten, JS akan bingung -->\n<input id="judulArtikel" ...>\n<input id="input-title" ...>    <!-- Berbeda format! -->\n<input id="InputTitle" ...>     <!-- Case-sensitive! -->\n\n<!-- ✅ BENAR — Konvensi camelCase konsisten -->\n<input  type="text"     id="inputTitle"    placeholder="Judul...">\n<textarea               id="inputContent"  placeholder="Konten..."></textarea>\n<input  type="text"     id="inputAuthor"   placeholder="Penulis...">\n<button type="submit"   id="btnSave">Simpan Artikel</button>\n\n<!-- Konvensi Penamaan yang Disarankan:\n  - Input fields  : inputNamaField   (inputTitle, inputContent)\n  - Tombol aksi   : btnNamaAksi      (btnSave, btnEdit, btnDelete)\n  - Container     : sectionNama      (sectionForm, sectionTable)\n  - Target render : tableBody, listContainer\n-->',
                        '```',
                        '---',

                        '### Target Kompetensi Praktikum',
                        'skill:100%:Hafal struktur boilerplate HTML5 tanpa melihat contoh:Wajib',
                        'skill:90%:Mampu buat form input dengan ID yang sistematis:Krusial',
                        'skill:85%:Mampu buat kerangka tabel dengan <tbody> kosong ber-ID:Persiapan JS',
                        'skill:100%:Memahami mengapa <script> selalu di bawah <body>:Konsep Penting',
                        '---',
                        '### Rincian Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Struktur Dasar", "Detail Tugas": "Membuat file index.html dengan boilerplate HTML5 lengkap dari memori — latih sampai hafal."}, {"Aktivitas": "Pembuatan Form", "Detail Tugas": "Membuat form input manajemen artikel (Judul & Konten) dengan ID sistematis sesuai konvensi."}, {"Aktivitas": "Wadah Tabel", "Detail Tugas": "Membuat kerangka tabel dengan thead lengkap dan <tbody id=\'tableBody\'> yang masih kosong."}, {"Aktivitas": "Verifikasi di Browser", "Detail Tugas": "Buka di browser, inspeksi elemen (F12), konfirmasi semua ID terdeteksi di tab Elements."}]',
                        '---'
                    ]
                },
                {
                    id: 'modul03',
                    title: 'Pertemuan 3: CSS3 — Desain & Layout Modern',
                    lines: [
                        '**Pertemuan 3: CSS3 — Desain Antarmuka & Tata Letak Modern**',
                        '*Kode yang benar tapi tampil buruk tidak akan digunakan siapapun.*',
                        '---',
                        'Fokus pada estetika, User Experience, dan tata letak modern menggunakan Flexbox serta Grid.',
                        'Mahasiswa membangun identitas visual untuk aplikasi CRUD yang adaptif di semua ukuran layar.',
                        '---',
                        '### Mengapa CSS Bukan Sekedar \'Dekorasi\'?',
                        'card:UX adalah Fungsionalitas:Tombol yang sulit ditekan, form yang membingungkan, atau tabel yang tidak bisa dibaca di mobile — ini bukan masalah estetika. Ini masalah fungsional yang membuat aplikasi tidak terpakai.',
                        'card:Mobile-First Bukan Pilihan:62% traffic web global berasal dari mobile. Membangun untuk desktop lalu menyesuaikan ke mobile selalu lebih sulit. Mulai dari mobile, scale-up ke desktop.',
                        'card:CSS Variables = Design System:Mendefinisikan warna dan font di :root adalah cara profesional. Mengubah tema aplikasi cukup ganti 3 variabel — bukan ratusan baris kode tersebar.',
                        '---',
                        '### Setup CSS: Variables, Reset & Base Style',
                        '```javascript',

                        'code:css:dracula:true:/* ===== CSS VARIABLES — Design System Niura ===== */\n:root {\n  --primary     : #2563eb;   /* Biru utama */\n  --primary-dark: #1d4ed8;   /* Hover state */\n  --danger      : #dc2626;   /* Tombol hapus */\n  --success     : #16a34a;   /* Notifikasi sukses */\n  --bg          : #f8fafc;   /* Background halaman */\n  --surface     : #ffffff;   /* Background card/form */\n  --text        : #1e293b;   /* Teks utama */\n  --text-muted  : #64748b;   /* Teks sekunder */\n  --border      : #e2e8f0;   /* Border elemen */\n  --radius      : 8px;       /* Border radius global */\n  --shadow      : 0 2px 8px rgba(0,0,0,.08);\n  --font        : \'Segoe UI\', system-ui, sans-serif;\n}\n\n/* ===== RESET ===== */\n*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\nbody { font-family: var(--font); background: var(--bg); color: var(--text); line-height: 1.6; }\n\n/* ===== TIPOGRAFI ===== */\nh1 { font-size: 1.5rem; font-weight: 700; color: var(--primary); }\nh2 { font-size: 1.1rem; font-weight: 600; margin-bottom: 1rem; }',
                        '```',
                        '---',
                        '### Flexbox untuk Layout Form & Tabel',
                        '```javascript',

                        'code:css:nord:true:/* ===== LAYOUT UTAMA ===== */\nheader {\n  background: var(--surface);\n  border-bottom: 1px solid var(--border);\n  padding: 1rem 2rem;\n  display: flex;\n  align-items: center;\n  gap: 1rem;\n  box-shadow: var(--shadow);\n}\n\nmain {\n  max-width: 900px;\n  margin: 2rem auto;\n  padding: 0 1rem;\n  display: flex;\n  flex-direction: column;\n  gap: 1.5rem;\n}\n\n/* ===== FORM STYLING ===== */\n#form-section {\n  background: var(--surface);\n  border-radius: var(--radius);\n  padding: 1.5rem;\n  box-shadow: var(--shadow);\n}\n\n#form-section form {\n  display: flex;\n  flex-direction: column;\n  gap: 0.75rem;\n}\n\ninput, textarea {\n  padding: 0.6rem 0.875rem;\n  border: 1px solid var(--border);\n  border-radius: var(--radius);\n  font-size: 0.9rem;\n  outline: none;\n  transition: border-color 0.2s;\n}\n\ninput:focus, textarea:focus {\n  border-color: var(--primary); /* Visual feedback saat aktif */\n}\n\n/* ===== TOMBOL ===== */\nbutton {\n  padding: 0.6rem 1.25rem;\n  border: none;\n  border-radius: var(--radius);\n  cursor: pointer;\n  font-weight: 600;\n  transition: background 0.2s, transform 0.1s;\n}\n\nbutton:active { transform: scale(0.97); } /* Micro-interaction klik */\n\n.btn-primary  { background: var(--primary); color: #fff; }\n.btn-primary:hover  { background: var(--primary-dark); }\n.btn-danger   { background: var(--danger);  color: #fff; }',
                        '```',
                        '---',
                        '### Tabel Responsif & Media Queries',
                        '```javascript',

                        'code:css:monokai:true:/* ===== TABEL DATA ===== */\n#table-section {\n  background: var(--surface);\n  border-radius: var(--radius);\n  padding: 1.5rem;\n  box-shadow: var(--shadow);\n  overflow-x: auto; /* Scroll horizontal di mobile */\n}\n\ntable { width: 100%; border-collapse: collapse; }\nth    { background: var(--bg); font-weight: 600; text-align: left; }\nth, td { padding: 0.75rem 1rem; border-bottom: 1px solid var(--border); }\n\n/* Zebra striping untuk keterbacaan */\ntbody tr:nth-child(even) { background: #f8fafc; }\ntbody tr:hover { background: #eff6ff; transition: background 0.15s; }\n\n/* ===== RESPONSIVITAS (Mobile First) ===== */\n/* Base style sudah untuk mobile */\n\n/* Tablet ke atas (≥ 640px) */\n@media (min-width: 640px) {\n  #form-section form { flex-direction: row; flex-wrap: wrap; }\n  #form-section form input { flex: 1; min-width: 200px; }\n  textarea { flex: 100%; }\n}\n\n/* Desktop ke atas (≥ 1024px) */\n@media (min-width: 1024px) {\n  main { padding: 0 2rem; }\n  h1   { font-size: 1.75rem; }\n}',
                        '```',
                        '---',
                        '### 3 Prinsip Desain Modern',
                        'card:Box Model Mastery:Semua elemen adalah kotak. Kuasai padding (ruang dalam), border, dan margin (ruang luar). Kesalahan margin/padding adalah sumber 80% masalah layout.',
                        'card:Flex & Grid:Flexbox untuk layout satu dimensi (baris atau kolom). Grid untuk layout dua dimensi. Untuk form dan tabel kita — Flexbox sudah lebih dari cukup.',
                        'card:Visual Feedback:Setiap aksi pengguna harus mendapat respons visual: hover berubah warna, focus menampilkan border, klik menampilkan scale-down. Ini membuat UI terasa hidup dan profesional.',
                        '---',
                        '### Kompetensi Estetika UI',
                        'skill:100%:CSS Variables sebagai Design System:Wajib Kuasai',
                        'skill:95%:Implementasi Flexbox untuk layout form:Utama',
                        'skill:85%:Styling komponen tabel dengan zebra striping:Detail',
                        'skill:75%:Media queries Mobile-First:Adaptif',
                        '---',
                        '### Panduan Praktikum CSS',
                        'table:[{"Aktivitas": "Buat style.css", "Detail Tugas": "Setup CSS Variables di :root dan global reset. Ini pondasi seluruh tampilan — jangan skip."}, {"Aktivitas": "Layout Header & Main", "Detail Tugas": "Styling header dan main container menggunakan Flexbox. Target: form ter-center dan rapi."}, {"Aktivitas": "Dekorasi Form & Tabel", "Detail Tugas": "Styling input, tombol, dan tabel. Tambahkan focus state pada input dan hover state pada tombol."}, {"Aktivitas": "Responsivitas", "Detail Tugas": "Tambahkan media query untuk breakpoint 640px dan 1024px. Test di DevTools Device Mode."}]',
                        '---'
                    ]
                },
                {
                    id: 'modul04',
                    title: 'Pertemuan 4: Manipulasi Layout & Komponen',
                    lines: [
                        '**Pertemuan 4: Manipulasi Layout & Komponen Antarmuka Dinamis**',
                        '*Komponen yang baik terasa invisible — pengguna fokus pada konten, bukan cara menggunakannya.*',
                        '---',
                        'Mempelajari teknik manipulasi visual untuk mendukung alur kerja CRUD.',
                        'Fokus pada Modal (jendela edit), Toast Notification (umpan balik aksi), dan transisi CSS yang membuat UI terasa profesional.',
                        '---',
                        '### Mengapa Kita Butuh Komponen-Komponen Ini?',
                        'card:Modal = Edit Tanpa Pindah Halaman:Tanpa modal, proses edit harus membuka halaman baru atau mengisi ulang form di tempat berbeda. Modal mempertahankan konteks pengguna — ia tetap \'di dalam\' tabel saat mengedit.',
                        'card:Toast = Konfirmasi yang Tidak Mengganggu:Browser alert() memblokir seluruh interaksi sampai di-klik. Toast muncul di pojok layar, memberi tahu pengguna, lalu menghilang sendiri. Standar UX modern.',
                        'card:CSS mengelola State, JS mengontrolnya:Modal secara default display:none. JavaScript hanya menambah/menghapus class. CSS yang mengurus bagaimana transisinya. Pemisahan tanggung jawab ini membuat kode jauh lebih bersih.',
                        '---',
                        '### HTML: Struktur Modal Edit',
                        '```javascript',

                        'code:html:dracula:true:<!-- Modal — letakkan sebelum penutup </body> -->\n<div id="modalOverlay" class="modal-overlay">\n  <div class="modal-box">\n\n    <div class="modal-header">\n      <h2>Edit Artikel</h2>\n      <button id="btnCloseModal" class="btn-close">&times;</button>\n    </div>\n\n    <div class="modal-body">\n      <!-- ID berbeda dari form utama agar tidak konflik -->\n      <input  type="hidden" id="editId">  <!-- Simpan ID tersembunyi -->\n      <input  type="text"   id="editTitle"   placeholder="Judul artikel...">\n      <textarea            id="editContent" placeholder="Konten artikel..."></textarea>\n    </div>\n\n    <div class="modal-footer">\n      <button id="btnUpdate" class="btn-primary">Simpan Perubahan</button>\n      <button id="btnCancel" class="btn-secondary">Batal</button>\n    </div>\n\n  </div>\n</div>\n\n<!-- Toast Notification -->\n<div id="toastNotif" class="toast"></div>',
                        '```',
                        '---',
                        '### CSS: Modal Overlay & Toast Notification',
                        '```javascript',

                        'code:css:nord:true:/* ===== MODAL ===== */\n.modal-overlay {\n  position: fixed;     /* Menutupi seluruh layar */\n  inset: 0;            /* top:0, right:0, bottom:0, left:0 */\n  background: rgba(0, 0, 0, 0.5);\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  z-index: 100;\n  opacity: 0;           /* Default: transparan */\n  pointer-events: none; /* Default: tidak bisa di-klik */\n  transition: opacity 0.25s ease;\n}\n\n.modal-overlay.active {\n  opacity: 1;\n  pointer-events: all; /* JS tambahkan class \'active\' untuk tampilkan */\n}\n\n.modal-box {\n  background: #fff;\n  border-radius: var(--radius);\n  padding: 1.5rem;\n  width: min(480px, 90vw); /* Responsif: maks 480px atau 90% lebar layar */\n  transform: translateY(-20px);\n  transition: transform 0.25s ease;\n}\n\n.modal-overlay.active .modal-box {\n  transform: translateY(0); /* Animasi slide-down saat aktif */\n}\n\n/* ===== TOAST NOTIFICATION ===== */\n.toast {\n  position: fixed;\n  bottom: 1.5rem;\n  right: 1.5rem;\n  padding: 0.75rem 1.25rem;\n  border-radius: var(--radius);\n  color: #fff;\n  font-weight: 600;\n  font-size: 0.875rem;\n  opacity: 0;\n  transform: translateY(20px);\n  transition: opacity 0.3s, transform 0.3s;\n  z-index: 200;\n}\n\n.toast.show {\n  opacity: 1;\n  transform: translateY(0);\n}\n\n.toast.success { background: var(--success); }\n.toast.error   { background: var(--danger);  }',
                        '```',
                        '---',
                        '### 3 Fitur Antarmuka Lanjutan',
                        'card:Modal System:position: fixed + z-index tinggi = elemen mengambang di atas semua konten. Opacity transition + pointer-events = animasi buka/tutup yang mulus tanpa JavaScript animation.',
                        'card:Toast Notification:Posisi fixed di pojok layar. JavaScript menambah class .show untuk memunculkan, setTimeout menghapusnya setelah 2.5 detik. Pengguna mendapat feedback tanpa interupsi.',
                        'card:Visual Hierarchy:Tipografi, kontras warna, dan spasi yang konsisten membantu pengguna memahami mana yang bisa diklik, mana yang penting, dan mana yang sebagai informasi saja.',
                        '---',
                        '### Preview JS: Cara Kontrol Modal & Toast (Dipraktikkan di P5)',
                        '```javascript',

                        'code:js:github-dark:true:// Ini preview — akan dikerjakan penuh di Pertemuan 5\n// Tujuan: pahami MENGAPA kita butuh struktur HTML & CSS yang sudah dibuat\n\nconst modalOverlay = document.getElementById(\'modalOverlay\');\nconst toastNotif   = document.getElementById(\'toastNotif\');\n\n// Tampilkan modal\nfunction openModal() {\n  modalOverlay.classList.add(\'active\'); // CSS yang mengurus animasinya\n}\n\n// Tutup modal\nfunction closeModal() {\n  modalOverlay.classList.remove(\'active\');\n}\n\n// Tampilkan toast notification\nfunction showToast(message, type = \'success\') {\n  toastNotif.textContent = message;\n  toastNotif.className   = `toast ${type} show`;\n  setTimeout(() => {\n    toastNotif.classList.remove(\'show\'); // Auto-hilang setelah 2.5 detik\n  }, 2500);\n}\n\n// Contoh penggunaan:\n// showToast(\'Artikel berhasil disimpan!\');\n// showToast(\'Judul tidak boleh kosong!\', \'error\');',
                        '```',
                        '---',
                        '### Target Pengembangan Komponen',
                        'skill:100%:HTML struktur modal lengkap dengan ID sistematis:Wajib',
                        'skill:95%:CSS modal overlay dengan opacity transition:Animasi CSS',
                        'skill:85%:CSS toast notification dengan auto-hide concept:UX Modern',
                        'skill:80%:Responsivitas modal menggunakan min():Mobile-Safe',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Buat Struktur Modal", "Detail Tugas": "Susun HTML modal form edit. Verifikasi semua ID input di modal tidak bentrok dengan ID form utama."}, {"Aktivitas": "CSS Overlay Effect", "Detail Tugas": "Implementasi opacity transition dan pointer-events. Test dengan menambah class \'active\' manual di DevTools."}, {"Aktivitas": "Styling Toast", "Detail Tugas": "Desain toast di pojok kanan bawah. Buat dua variant: .success (hijau) dan .error (merah)."}, {"Aktivitas": "Uji Visual", "Detail Tugas": "Toggle class \'active\' pada modal dan \'show\' pada toast via DevTools Console. Konfirmasi animasi berjalan mulus."}]',
                        '---'
                    ]
                }
            ]
        },
        {
            name: 'Bagian 2: JavaScript & Logika UI',
            items: [
                {
                    id: 'modul05',
                    title: 'Pertemuan 5: Vanilla JS & Manipulasi DOM',
                    lines: [
                        '**Pertemuan 5: Vanilla JavaScript Dasar & Manipulasi DOM**',
                        '*HTML adalah tubuh. CSS adalah penampilan. JavaScript adalah otaknya.*',
                        '---',
                        'Titik balik dari desain menuju pemrograman. Mahasiswa mempelajari dasar Vanilla JS, teknik seleksi elemen DOM, dan penanganan interaksi pengguna melalui Event Listeners.',
                        'Semua yang dibangun di P2–P4 kini mulai \'hidup\'.',
                        '---',
                        '### Mengapa Harus Mengerti DOM Manipulation?',
                        'card:HTML adalah Statis, DOM adalah Dinamis:HTML yang Anda tulis adalah template. DOM adalah representasi hidup di memori browser. JavaScript memanipulasi DOM — bukan file HTML langsung. Memahami perbedaan ini mencegah kebingungan besar.',
                        'card:getElementById vs querySelector:getElementById(\'#id\') lebih cepat untuk satu elemen spesifik. querySelector() lebih fleksibel (bisa gunakan CSS selector apapun). Untuk proyek kita, getElementById sudah ideal.',
                        'card:preventDefault() Wajib pada Form:Tanpa preventDefault(), submit form memuat ulang halaman — menghapus semua data di memori. Ini baris kode pertama yang wajib ada di setiap event handler form.',
                        '---',
                        '### Koneksi HTML ke JavaScript — Pola Dasar',
                        '```javascript',

                        'code:js:dracula:true:// ===== STEP 1: SELEKSI ELEMEN DOM =====\n// Hubungkan variabel JS ke elemen HTML via ID\n// Letakkan ini di bagian ATAS file app.js\n\nconst articleForm   = document.getElementById(\'articleForm\');\nconst inputTitle    = document.getElementById(\'inputTitle\');\nconst inputContent  = document.getElementById(\'inputContent\');\nconst btnSave       = document.getElementById(\'btnSave\');\nconst tableBody     = document.getElementById(\'tableBody\');\nconst modalOverlay  = document.getElementById(\'modalOverlay\');\nconst toastNotif    = document.getElementById(\'toastNotif\');\n\n// Verifikasi: semua harus menampilkan elemen, bukan null\nconsole.log(\'Form    :\', articleForm);\nconsole.log(\'Input   :\', inputTitle);\nconsole.log(\'Table   :\', tableBody);\n// Jika ada yang null = ID di HTML tidak cocok dengan yang di atas!\n\n// ===== STEP 2: EVENT LISTENERS =====\n// Daftarkan fungsi yang akan dipanggil saat event terjadi\n\narticleForm.addEventListener(\'submit\', function(event) {\n  event.preventDefault(); // WAJIB — cegah reload halaman!\n  console.log(\'Form di-submit!\');\n  console.log(\'Judul :\', inputTitle.value);\n  console.log(\'Konten:\', inputContent.value);\n});',
                        '```',
                        '---',
                        '### Manipulasi DOM — Read, Write, Style',
                        '```javascript',

                        'code:js:nord:true:// ===== MEMBACA DATA DARI ELEMEN =====\nconst judul   = inputTitle.value;    // Ambil teks yang diketik\nconst konten  = inputContent.value;  // Ambil isi textarea\n\n// ===== MENULIS DATA KE ELEMEN =====\ntableBody.innerHTML = \'<tr><td>Test</td></tr>\'; // Ganti seluruh isi\ndocument.getElementById(\'jumlahData\').textContent = \'5 artikel\'; // Ganti teks\n\n// ===== MANIPULASI STYLE via CLASS =====\nmodalOverlay.classList.add(\'active\');     // Tampilkan modal\nmodalOverlay.classList.remove(\'active\'); // Sembunyikan modal\nmodalOverlay.classList.toggle(\'active\'); // Toggle buka/tutup\n\n// ===== PRAKTIK: Kontrol Modal via Event =====\nbtnSave.addEventListener(\'click\', function() {\n  // Ambil nilai input\n  const title   = inputTitle.value.trim();\n  const content = inputContent.value.trim();\n\n  // Validasi sederhana\n  if (!title || !content) {\n    alert(\'Judul dan konten wajib diisi!\'); // Sementara pakai alert\n    return; // Hentikan eksekusi\n  }\n\n  // Tampilkan hasil di console (belum ke tabel)\n  console.log({ title, content });\n});',
                        '```',
                        '---',
                        '### 3 Konsep Inti JavaScript',
                        'card:DOM Selection:getElementById() adalah gerbang antara HTML dan JS. Setiap elemen yang akan dimanipulasi harus diseleksi dulu. Variabel ini biasanya dideklarasikan di bagian atas file.',
                        'card:Event Listeners:addEventListener(event, callback) mendaftarkan fungsi yang dipanggil saat event terjadi. Event umum: \'click\', \'submit\', \'keyup\', \'change\'. Callback menerima objek event.',
                        'card:Data Handling:.value mengambil teks dari input/textarea. .trim() menghapus spasi di awal/akhir. .textContent dan .innerHTML menulis ke elemen. Ini tiga properti paling sering digunakan.',
                        '---',
                        '### Target Pembelajaran Logika',
                        'skill:100%:Mampu seleksi semua elemen DOM yang dibutuhkan:Wajib',
                        'skill:90%:Mampu daftarkan event listener pada form dan tombol:Krusial',
                        'skill:100%:Selalu gunakan event.preventDefault() pada form submit:Wajib',
                        'skill:85%:Mampu baca .value dan tulis ke .innerHTML / .textContent:Penting',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Hello Console", "Deskripsi Tugas": "Tulis console.log(\'Aplikasi dimulai!\') dan konfirmasi tampil di DevTools Console. Test koneksi script."}, {"Aktivitas": "Seleksi Semua Elemen", "Deskripsi Tugas": "Deklarasikan variabel untuk semua elemen DOM yang dibutuhkan. Log ke console, pastikan tidak ada yang null."}, {"Aktivitas": "Tangkap Data Form", "Deskripsi Tugas": "Buat form submit handler. Tangkap .value dari inputTitle dan inputContent. Log hasilnya."}, {"Aktivitas": "Kontrol Modal", "Deskripsi Tugas": "Buat fungsi openModal() dan closeModal() menggunakan classList.add/remove. Ikat ke tombol."}]',
                        '---'
                    ]
                },
                {
                    id: 'modul06',
                    title: 'Pertemuan 6: Interaktivitas & Logika Render',
                    lines: [
                        '**Pertemuan 6: Interaktivitas Lanjutan & Logika Render Antarmuka**',
                        '*Data di array, tampilan di tabel — fungsi renderTable() adalah jembatan di antaranya.*',
                        '---',
                        'Tahap krusial sebelum penyimpanan permanen. Mahasiswa mempelajari logika kondisional untuk validasi, teknik looping untuk render tabel, dan modularitas fungsi.',
                        'Setelah pertemuan ini, data sudah bisa masuk dan tampil — hanya belum tersimpan.',
                        '---',
                        '### Konsep Kunci Pertemuan Ini',
                        'card:Array sebagai Sumber Kebenaran:Jangan pernah baca data langsung dari DOM. Simpan data di array JavaScript, biarkan renderTable() yang selalu mengubah array menjadi HTML. Ini pola yang digunakan semua framework modern.',
                        'card:Re-render setelah setiap Perubahan:Setiap kali data ditambah, dihapus, atau diubah — selalu bersihkan tableBody dan render ulang dari awal. Ini lebih aman daripada mencoba memodifikasi baris tabel secara individual.',
                        'card:Modular = Bisa Dipakai Ulang:Fungsi clearForm(), renderTable(), dan showToast() yang dibuat sekali akan dipanggil berkali-kali dari berbagai tempat. Ini prinsip DRY (Don\'t Repeat Yourself) yang paling mendasar.',
                        '---',
                        '### Fungsi renderTable() — Jantung Aplikasi',
                        '```javascript',

                        'code:js:dracula:true:// Array sebagai sumber data (sementara, akan pindah ke LocalStorage di P10)\nlet articles = [];\n\n// ===== FUNGSI RENDER — Dipanggil setiap kali data berubah =====\nfunction renderTable() {\n  // Selalu bersihkan dulu sebelum render ulang\n  tableBody.innerHTML = \'\';\n\n  // Handle empty state\n  if (articles.length === 0) {\n    tableBody.innerHTML = `\n      <tr>\n        <td colspan="4" style="text-align:center; color:#94a3b8; padding:2rem">\n          Belum ada artikel. Tambahkan artikel pertama Anda!\n        </td>\n      </tr>\n    `;\n    return;\n  }\n\n  // Render setiap item dari array menggunakan forEach\n  articles.forEach((article, index) => {\n    const row = document.createElement(\'tr\');\n    row.innerHTML = `\n      <td>${index + 1}</td>\n      <td>${article.title}</td>\n      <td>${article.content.substring(0, 80)}...</td>\n      <td>\n        <button onclick="setupEdit(${article.id})"   class="btn-primary" >Edit</button>\n        <button onclick="deleteArticle(${article.id})" class="btn-danger"  >Hapus</button>\n      </td>\n    `;\n    tableBody.appendChild(row);\n  });\n}',
                        '```',
                        '---',
                        '### Fungsi addArticle() + Validasi + Utilities',
                        '```javascript',

                        'code:js:nord:true:// ===== TAMBAH DATA (CREATE) =====\narticleForm.addEventListener(\'submit\', function(e) {\n  e.preventDefault();\n\n  const title   = inputTitle.value.trim();\n  const content = inputContent.value.trim();\n\n  // Validasi: jangan izinkan data kosong\n  if (!title) {\n    showToast(\'Judul artikel wajib diisi!\', \'error\');\n    inputTitle.focus(); // Kembalikan fokus ke field yang bermasalah\n    return;\n  }\n  if (!content) {\n    showToast(\'Konten artikel wajib diisi!\', \'error\');\n    inputContent.focus();\n    return;\n  }\n\n  // Buat object artikel baru\n  const newArticle = {\n    id      : Date.now(),        // ID unik berbasis timestamp\n    title   : title,\n    content : content,\n    createdAt: new Date().toLocaleDateString(\'id-ID\')\n  };\n\n  articles.push(newArticle);   // Tambahkan ke array\n  renderTable();                // Render ulang tabel\n  clearForm();                  // Bersihkan form\n  showToast(\'Artikel berhasil ditambahkan!\');\n});\n\n// ===== UTILITY FUNCTIONS =====\nfunction clearForm() {\n  inputTitle.value   = \'\';\n  inputContent.value = \'\';\n  inputTitle.focus(); // Siap untuk input berikutnya\n}\n\n// ===== HAPUS DATA (DELETE) =====\nfunction deleteArticle(id) {\n  // Filter: buat array baru tanpa item yang ID-nya cocok\n  articles = articles.filter(a => a.id !== id);\n  renderTable();\n  showToast(\'Artikel berhasil dihapus!\', \'success\');\n}\n\n// ===== INISIALISASI =====\nrenderTable(); // Panggil saat load untuk tampilkan empty state',
                        '```',
                        '---',
                        '### 3 Pilar Logika Pemrograman UI',
                        'card:Looping & Render:forEach() + Template Literals (backtick) adalah kombinasi terkuat untuk mengubah data array menjadi baris HTML. .map().join(\'\') adalah alternatif yang lebih fungsional.',
                        'card:Validasi Input:.trim() untuk hapus spasi, truthy check (!title) untuk cek kosong. Validasi sebelum memproses data mencegah data sampah masuk ke array dan merusak tampilan.',
                        'card:Class Manipulation:classList.add/remove/toggle mengontrol state visual komponen. Ini koneksi antara CSS yang kita buat di P4 dengan JavaScript. CSS mengatur tampilan, JS mengontrol kapan tampil.',
                        '---',
                        '### Target Penguasaan',
                        'skill:90%:Mampu render array ke tabel menggunakan forEach:Kunci Utama',
                        'skill:85%:Validasi input tanpa alert() default browser:UX Modern',
                        'skill:80%:Fungsi modular: clearForm, renderTable, showToast:Clean Code',
                        'skill:85%:Delete data dengan .filter() berdasarkan ID:Logic',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Render Dummy Data", "Deskripsi Tugas": "Isi array articles dengan 3 objek dummy manual. Panggil renderTable() dan konfirmasi tampil di tabel."}, {"Aktivitas": "Form ke Tabel", "Deskripsi Tugas": "Implementasikan form submit handler: tangkap input, buat object, push ke array, renderTable(), clearForm()."}, {"Aktivitas": "Fungsi Delete", "Deskripsi Tugas": "Implementasikan deleteArticle(id) menggunakan .filter(). Test hapus setiap baris dan pastikan tabel update."}, {"Aktivitas": "Empty State", "Deskripsi Tugas": "Tambahkan tampilan \'belum ada data\' saat array kosong. Hapus semua artikel dan konfirmasi empty state muncul."}]',
                        '---'
                    ]
                },
                {
                    id: 'modul07',
                    title: 'Pertemuan 7: Review & Integrasi Prototipe',
                    lines: [
                        '**Pertemuan 7: Review & Integrasi Prototipe Antarmuka**',
                        '*Satu aplikasi yang bekerja sempurna lebih berharga dari sepuluh fitur yang setengah jadi.*',
                        '---',
                        'Sesi penguatan untuk menyatukan HTML5, CSS3, dan Vanilla JS menjadi satu kesatuan.',
                        'Fokus pada sinkronisasi komponen UI dengan logika program dan persiapan UTS Live Coding.',
                        '---',
                        '### Apa yang Harus Sudah Bisa Anda Lakukan?',
                        'card:HTML + CSS: Antarmuka Siap:Form input dengan ID sistematis, tabel dengan <tbody> kosong, modal overlay dengan CSS transition, dan toast notification — semuanya terhubung dan tampil rapi di mobile.',
                        'card:JavaScript: Data Mengalir:articles array sebagai sumber data, renderTable() yang otomatis update tampilan, form submit menambah data, tombol hapus mengfilter array — semua terhubung tanpa reload halaman.',
                        'card:Yang Belum Ada: Persistensi:Refresh halaman = data hilang. Ini normal dan disengaja — persistensi via LocalStorage adalah materi Pertemuan 10. Untuk UTS, data sementara di memori sudah cukup.',
                        '---',
                        '### Checklist Kode: Pola yang Harus Ada di app.js',
                        '```javascript',

                        'code:js:monokai:true:// ✅ CHECKLIST KODE WAJIB — Verifikasi sebelum UTS\n\n// 1. Deklarasi variabel DOM (atas file)\nconst articleForm  = document.getElementById(\'articleForm\');  // ✅?\nconst tableBody    = document.getElementById(\'tableBody\');    // ✅?\n// ... (semua elemen terdeklarasi)\n\n// 2. Array data\nlet articles = [];  // ✅ Pakai \'let\', bukan \'const\'\n\n// 3. Fungsi render\nfunction renderTable() { /* ... */ }  // ✅ Ada empty state?\n\n// 4. Fungsi utility\nfunction clearForm()          { /* ... */ }  // ✅?\nfunction showToast(msg, type) { /* ... */ }  // ✅?\nfunction openModal()          { /* ... */ }  // ✅?\nfunction closeModal()         { /* ... */ }  // ✅?\n\n// 5. Event listeners\narticleForm.addEventListener(\'submit\', function(e) {\n  e.preventDefault();  // ✅ WAJIB ADA\n  // ... validasi dan addArticle\n});\n\n// 6. Inisialisasi\nrenderTable(); // ✅ Dipanggil di akhir file untuk tampilkan empty state',
                        '```',
                        '---',
                        '### Aktivitas \'The Integration Lab\'',
                        'table:[{"Aktivitas": "Bug Fixing Session", "Deskripsi Tugas": "Identifikasi dan perbaiki kesalahan: tombol hapus tidak berfungsi, modal tidak menutup, atau form tidak clear setelah submit."}, {"Aktivitas": "Styling Polish", "Deskripsi Tugas": "Haluskan transisi CSS pada modal (opacity + transform). Pastikan toast muncul dan menghilang dengan animasi."}, {"Aktivitas": "Data Flow Test", "Deskripsi Tugas": "Test lengkap: tambah 3 artikel → hapus artikel ke-2 → tambah lagi → hapus semua. Tidak boleh ada error di console."}, {"Aktivitas": "Code Documentation", "Deskripsi Tugas": "Tambahkan komentar pada setiap fungsi. Format: // Fungsi: [nama] — [tujuan]. Nilai kerapian kode 5% di UTS."}]',
                        '---',
                        '### Kesiapan UTS',
                        'skill:100%:Struktur & Semantik HTML5 + ID sistematis:Harus Solid',
                        'skill:100%:CSS responsif + komponen modal & toast:Harus Polished',
                        'skill:90%:Logika JS: render, add, delete, validasi, clear:Harus Integrated',
                        '---'
                    ]
                },
                {
                    id: 'modul08',
                    title: 'Pertemuan 8: UTS — Evaluasi Tengah Semester',
                    lines: [
                        '**Pertemuan 8: Evaluasi Tengah Semester (UTS)**',
                        '*Bukan ujian hapalan — ini ujian apakah tangan Anda sudah bisa membangun.*',
                        '---',
                        'UTS berbasis Live Coding: membangun modul manajemen data interaktif dalam waktu terbatas.',
                        'Semua yang diuji sudah dipraktikkan di P1–P7. Tidak ada surpris — hanya eksekusi.',
                        '---',
                        '### Strategi Sukses UTS Live Coding',
                        'card:Mulai dari HTML, Bukan JS:Bangun struktur dan ID dulu — ini fondasi yang JS akan bergantung. Coding JS tanpa HTML siap adalah resep frustasi. Alokasi 60 menit pertama untuk HTML + CSS.',
                        'card:Fungsi Kecil, Test Sering:Setelah setiap fungsi selesai, test di console. Jangan tulis 100 baris sekaligus baru test. Bug yang ditemukan lebih awal 10x lebih mudah diperbaiki.',
                        'card:F12 adalah Penyelamat:DevTools Console menampilkan semua error dengan baris yang tepat. Jika ada yang tidak bekerja, Console adalah tempat pertama yang diperiksa — selalu.',
                        '---',
                        '### Rubrik Penilaian UTS',
                        'table:[{"Kriteria": "Struktur HTML", "Bobot": "20%", "Indikator": "Tag semantik lengkap, ID/Class terorganisir, <tbody> kosong siap diisi JS."}, {"Kriteria": "Desain CSS", "Bobot": "25%", "Indikator": "CSS Variables terdefinisi, Flexbox/Grid diterapkan, responsif di mobile."}, {"Kriteria": "Manipulasi DOM", "Bobot": "30%", "Indikator": "renderTable() akurat, fungsi add/delete berjalan, tidak ada null di console."}, {"Kriteria": "Logika & Validasi", "Bobot": "20%", "Indikator": "Validasi input tanpa alert() default, preventDefault() pada form submit."}, {"Kriteria": "Kerapian Kode", "Bobot": "5%", "Indikator": "Komentar pada setiap fungsi, penamaan variabel deskriptif, tidak ada code yang kotor."}]',
                        '---',
                        '### Template Awal yang Boleh Dihafal',
                        '```javascript',

                        'code:js:github-dark:true:// Template app.js — Struktur minimal yang harus bisa ditulis dari memori\n\n// === DOM ELEMENTS ===\nconst articleForm  = document.getElementById(\'articleForm\');\nconst inputTitle   = document.getElementById(\'inputTitle\');\nconst inputContent = document.getElementById(\'inputContent\');\nconst tableBody    = document.getElementById(\'tableBody\');\nconst modalOverlay = document.getElementById(\'modalOverlay\');\nconst toastNotif   = document.getElementById(\'toastNotif\');\n\n// === STATE ===\nlet articles = [];\n\n// === RENDER ===\nfunction renderTable() {\n  tableBody.innerHTML = \'\';\n  if (articles.length === 0) {\n    tableBody.innerHTML = \'<tr><td colspan="4">Belum ada data.</td></tr>\';\n    return;\n  }\n  articles.forEach((a, i) => {\n    const tr = document.createElement(\'tr\');\n    tr.innerHTML = `<td>${i+1}</td><td>${a.title}</td><td>${a.content}</td>\n      <td>\n        <button onclick="setupEdit(${a.id})">Edit</button>\n        <button onclick="deleteArticle(${a.id})">Hapus</button>\n      </td>`;\n    tableBody.appendChild(tr);\n  });\n}\n\n// === UTILITIES ===\nfunction clearForm()  { inputTitle.value = \'\'; inputContent.value = \'\'; }\nfunction openModal()  { modalOverlay.classList.add(\'active\');    }\nfunction closeModal() { modalOverlay.classList.remove(\'active\'); }\nfunction showToast(msg, type = \'success\') {\n  toastNotif.textContent = msg;\n  toastNotif.className = `toast ${type} show`;\n  setTimeout(() => toastNotif.classList.remove(\'show\'), 2500);\n}\n\n// === CRUD ===\narticleForm.addEventListener(\'submit\', e => {\n  e.preventDefault();\n  const title   = inputTitle.value.trim();\n  const content = inputContent.value.trim();\n  if (!title || !content) { showToast(\'Isi semua field!\', \'error\'); return; }\n  articles.push({ id: Date.now(), title, content });\n  renderTable(); clearForm(); showToast(\'Artikel disimpan!\');\n});\n\nfunction deleteArticle(id) {\n  articles = articles.filter(a => a.id !== id);\n  renderTable(); showToast(\'Artikel dihapus!\');\n}\n\n// === INIT ===\nrenderTable();',
                        '```',
                        '---',
                        '### Alokasi Waktu UTS (150 Menit)',
                        'skill:40%:HTML + CSS Struktur & Styling:60 Menit',
                        'skill:50%:JavaScript DOM + Logika CRUD:75 Menit',
                        'skill:10%:Testing, Finishing & Komentar:15 Menit',
                        '---'
                    ]
                }
            ]
        },
        {
            name: 'Bagian 3: Data, Storage & Async',
            items: [
                {
                    id: 'modul09',
                    title: 'Pertemuan 9: Advanced JS — Object, Array & JSON',
                    lines: [
                        '**Pertemuan 9: Advanced JS — Object, Array, & JSON**',
                        '*Sebelum data bisa disimpan, data harus dipahami strukturnya terlebih dahulu.*',
                        '---',
                        'Memasuki paruh kedua dengan fokus pada pengelolaan data kompleks.',
                        'Mahasiswa mendalami Array of Objects, transformasi JSON, dan Higher-Order Functions yang menjadi standar industri.',
                        '---',
                        '### Mengapa Ini Penting Sebelum LocalStorage?',
                        'card:LocalStorage hanya Menyimpan String:Anda tidak bisa menyimpan array atau object langsung ke LocalStorage. Anda harus mengubahnya menjadi JSON string dulu. Tanpa memahami JSON.stringify dan JSON.parse, LocalStorage tidak akan berfungsi.',
                        'card:Higher-Order Functions adalah Standar:filter(), map(), dan find() bukan sintaks mewah — ini cara developer profesional memproses data. Kode dengan for-loop manual lebih panjang, lebih rentan bug, dan lebih sulit dibaca.',
                        'card:Date.now() = ID Unik Gratis:Database punya auto-increment. Kita punya Date.now() yang mengembalikan timestamp milidetik unik. Sempurna sebagai ID — tidak ada dua artikel yang bisa dibuat di milidetik yang sama.',
                        '---',
                        '### JSON: Serialisasi & Deserialisasi',
                        '```javascript',

                        'code:js:dracula:true:// ===== JSON MASTERY =====\n\nconst articles = [\n  { id: 1706000001000, title: \'HTML Dasar\',    content: \'Belajar tag semantik...\' },\n  { id: 1706000002000, title: \'CSS Flexbox\',   content: \'Layout responsif...\' },\n  { id: 1706000003000, title: \'JavaScript DOM\', content: \'Manipulasi elemen...\' }\n];\n\n// STRINGIFY: Array/Object → String (untuk disimpan)\nconst jsonString = JSON.stringify(articles);\nconsole.log(typeof jsonString); // \'string\'\nconsole.log(jsonString);\n// Output: \'[{"id":1706000001000,"title":"HTML Dasar",...}]\'\n\n// PARSE: String → Array/Object (untuk digunakan)\nconst parsedArticles = JSON.parse(jsonString);\nconsole.log(typeof parsedArticles); // \'object\' (array)\nconsole.log(parsedArticles[0].title); // \'HTML Dasar\'\n\n// ⚠️ Siklus yang akan digunakan di LocalStorage:\n// Simpan : localStorage.setItem(\'articles\', JSON.stringify(articles))\n// Ambil  : JSON.parse(localStorage.getItem(\'articles\'))',
                        '```',
                        '---',
                        '### Higher-Order Functions — Cara Profesional Proses Data',
                        '```javascript',

                        'code:js:nord:true:// ===== .filter() — Hapus berdasarkan ID =====\n// Mengembalikan array baru tanpa item yang id-nya cocok\nfunction deleteArticle(id) {\n  articles = articles.filter(article => article.id !== id);\n  // Semua artikel KECUALI yang id-nya sama dengan parameter\n}\n\n// ===== .find() — Cari satu item berdasarkan ID =====\n// Mengembalikan item pertama yang cocok, atau undefined\nfunction setupEdit(id) {\n  const article = articles.find(a => a.id === id);\n  if (article) {\n    editTitle.value   = article.title;\n    editContent.value = article.content;\n    editId.value      = article.id; // Simpan ID di hidden input\n    openModal();\n  }\n}\n\n// ===== .map() — Transformasi seluruh array =====\n// Mengembalikan array baru dengan setiap item ditransformasi\nconst titleList = articles.map(a => a.title);\n// [\'HTML Dasar\', \'CSS Flexbox\', \'JavaScript DOM\']\n\nconst tableRows = articles.map((a, i) =>\n  `<tr><td>${i+1}</td><td>${a.title}</td></tr>`\n).join(\'\');\n// Alternatif renderTable() yang lebih fungsional\n\n// ===== .findIndex() — Cari posisi untuk Update =====\nfunction updateArticle(id, newTitle, newContent) {\n  const index = articles.findIndex(a => a.id === id);\n  if (index !== -1) {\n    articles[index].title   = newTitle;\n    articles[index].content = newContent;\n    renderTable();\n  }\n}',
                        '```',
                        '---',
                        '### 3 Pilar Pengolahan Data',
                        'card:JSON Mastery:JSON.stringify(data) untuk simpan — JSON.parse(string) untuk baca. Ini dua fungsi terpenting untuk integrasi LocalStorage dan Fetch API.',
                        'card:Array Methods:.filter() untuk hapus, .find() untuk cari satu item, .findIndex() untuk update, .map() untuk transformasi. Kuasai keempatnya dan tidak ada operasi data yang tidak bisa Anda lakukan.',
                        'card:Unique ID via Date.now():Date.now() mengembalikan milidetik sejak 1 Jan 1970. Angka ini unik per transaksi. Untuk aplikasi single-user di browser, ini solusi ID yang sempurna dan sederhana.',
                        '---',
                        '### Target Kompetensi Data',
                        'skill:100%:Hafal siklus JSON.stringify ↔ JSON.parse:Wajib untuk LocalStorage',
                        'skill:90%:Gunakan .filter() untuk delete, .find() untuk edit:Sudah di P6, kuatkan',
                        'skill:85%:Gunakan .findIndex() untuk update data di array:Kunci fungsi Update',
                        'skill:90%:Struktur object: id, title, content, createdAt:Standar proyek',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Object Construction", "Deskripsi Tugas": "Buat object artikel dengan id: Date.now(), title, content, createdAt. Log ke console dan inspeksi strukturnya."}, {"Aktivitas": "JSON Roundtrip", "Deskripsi Tugas": "Stringify array articles ke string, log hasilnya, lalu parse kembali. Konfirmasi data tidak berubah setelah roundtrip."}, {"Aktivitas": "Array Filtering", "Deskripsi Tugas": "Gunakan .filter() untuk hapus artikel berdasarkan ID. Log array sebelum dan sesudah untuk verifikasi."}, {"Aktivitas": "Update dengan findIndex", "Deskripsi Tugas": "Implementasikan fungsi updateArticle() menggunakan .findIndex(). Test update judul artikel pertama."}]',
                        '---'
                    ]
                },
                {
                    id: 'modul10',
                    title: 'Pertemuan 10: Persistensi Data dengan LocalStorage',
                    lines: [
                        '**Pertemuan 10: Persistensi Data dengan LocalStorage**',
                        '*Data yang hilang saat refresh bukan aplikasi — itu hanya demo. Sekarang kita buat aplikasi sungguhan.*',
                        '---',
                        'Mahasiswa mempelajari Web Storage API untuk menyimpan data permanen di sisi klien.',
                        'Setelah pertemuan ini, artikel yang Anda tambahkan akan tetap ada meski browser ditutup dan dibuka kembali.',
                        '---',
                        '### Memahami LocalStorage dengan Benar',
                        'card:LocalStorage bukan Database:LocalStorage adalah pasangan key-value di browser — seperti catatan tempel di komputer pengguna. Kapasitasnya ~5MB per domain, tidak sinkron antar perangkat, dan tidak aman untuk data sensitif.',
                        'card:Kenapa Bukan SessionStorage?:SessionStorage hilang saat tab ditutup — sama seperti array JavaScript kita selama ini. LocalStorage bertahan sampai pengguna manual menghapusnya. Untuk aplikasi CRUD kita, LocalStorage adalah pilihan tepat.',
                        'card:Pola Sinkronisasi yang Benar:Jangan simpan ke storage di setiap keystroke. Pola yang benar: (1) Muat dari storage saat startup, (2) Modifikasi array di memori, (3) Simpan ke storage setelah setiap perubahan, (4) Render dari array.',
                        '---',
                        '### Pola CRUD dengan LocalStorage — Implementasi Lengkap',
                        '```javascript',

                        'code:js:dracula:true:// ===== KONSTANTA KUNCI STORAGE =====\nconst STORAGE_KEY = \'niura_articles\';\n\n// ===== MUAT DATA DARI STORAGE =====\n// Dipanggil sekali saat aplikasi pertama dijalankan\nfunction loadFromStorage() {\n  const raw = localStorage.getItem(STORAGE_KEY);\n  return raw ? JSON.parse(raw) : []; // Jika kosong, mulai dengan array kosong\n}\n\n// ===== SIMPAN DATA KE STORAGE =====\n// Dipanggil setiap kali array berubah\nfunction saveToStorage() {\n  localStorage.setItem(STORAGE_KEY, JSON.stringify(articles));\n}\n\n// ===== INISIALISASI — MUAT SAAT STARTUP =====\nlet articles = loadFromStorage();\nrenderTable(); // Tampilkan data yang sudah ada\n\n// ===== UPDATE SEMUA FUNGSI CRUD =====\n\n// Tambah artikel\narticleForm.addEventListener(\'submit\', e => {\n  e.preventDefault();\n  const title   = inputTitle.value.trim();\n  const content = inputContent.value.trim();\n  if (!title || !content) { showToast(\'Isi semua field!\', \'error\'); return; }\n\n  articles.push({\n    id: Date.now(), title, content,\n    createdAt: new Date().toLocaleDateString(\'id-ID\')\n  });\n\n  saveToStorage(); // ← TAMBAHAN: simpan ke storage\n  renderTable();\n  clearForm();\n  showToast(\'Artikel disimpan!\');\n});\n\n// Hapus artikel\nfunction deleteArticle(id) {\n  articles = articles.filter(a => a.id !== id);\n  saveToStorage(); // ← TAMBAHAN: simpan ke storage\n  renderTable();\n  showToast(\'Artikel dihapus!\');\n}',
                        '```',
                        '---',
                        '### Inspeksi LocalStorage di DevTools',
                        '```javascript',

                        'code:bash:nord:false:# Cara melihat data LocalStorage di browser:\n# 1. Buka DevTools (F12)\n# 2. Klik tab "Application" (Chrome) atau "Storage" (Firefox)\n# 3. Expand "Local Storage" di sidebar kiri\n# 4. Klik "http://localhost:5500" (atau URL yang Anda gunakan)\n# 5. Lihat key \'niura_articles\' dan nilainya (JSON string)\n\n# Cara clear data manual untuk testing:\n# Method 1: Klik kanan pada key → Delete\n# Method 2: Via Console:\nlocalStorage.removeItem(\'niura_articles\');\n# Method 3: Clear semua storage domain:\nlocalStorage.clear();\n\n# Cara verifikasi data tersimpan via Console:\nJSON.parse(localStorage.getItem(\'niura_articles\'));',
                        '```',
                        '---',
                        '### 4 Method LocalStorage yang Wajib Dikuasai',
                        'table:[{"Method": "localStorage.setItem(key, value)", "Fungsi": "Simpan data. Value HARUS string — gunakan JSON.stringify untuk array/object.", "Contoh": "setItem(\'niura_articles\', JSON.stringify(articles))"}, {"Method": "localStorage.getItem(key)", "Fungsi": "Baca data. Mengembalikan string atau null jika key tidak ada.", "Contoh": "JSON.parse(getItem(\'niura_articles\')) || []"}, {"Method": "localStorage.removeItem(key)", "Fungsi": "Hapus satu key beserta nilainya.", "Contoh": "removeItem(\'niura_articles\')"}, {"Method": "localStorage.clear()", "Fungsi": "Hapus SEMUA data LocalStorage domain ini. Gunakan dengan hati-hati.", "Contoh": "Hanya untuk reset total saat development"}]',
                        '---',
                        '### Target Persistensi Data',
                        'skill:100%:Implementasikan loadFromStorage() & saveToStorage():Kunci Pertemuan Ini',
                        'skill:95%:Setiap mutasi array selalu diikuti saveToStorage():Disiplin Wajib',
                        'skill:100%:Data tetap ada setelah browser ditutup & dibuka:Bukti Berhasil',
                        'skill:85%:Mampu inspect dan clear data via DevTools:Debug Skill',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Fungsi Load & Save", "Deskripsi Tugas": "Implementasikan loadFromStorage() dan saveToStorage(). Test: tambah artikel, refresh, konfirmasi data masih ada."}, {"Aktivitas": "Update Semua CRUD", "Deskripsi Tugas": "Tambahkan saveToStorage() setelah setiap operasi add, delete, dan update. Tidak ada exception."}, {"Aktivitas": "Inspeksi DevTools", "Deskripsi Tugas": "Buka tab Application → Local Storage. Verifikasi key \'niura_articles\' berisi JSON array yang benar."}, {"Aktivitas": "Stress Test", "Deskripsi Tugas": "Tambah 5 artikel, hapus 2, update 1, tutup browser, buka kembali. Data harus sama persis."}]',
                        '---'
                    ]
                },
                {
                    id: 'modul11',
                    title: 'Pertemuan 11: Asynchronous JS & Fetch API',
                    lines: [
                        '**Pertemuan 11: Asynchronous JS & Fetch API**',
                        '*Aplikasi yang \'membekukan\' layar saat loading data adalah aplikasi yang belum memahami async.*',
                        '---',
                        'Transisi dari data lokal statis menuju pengambilan data dinamis dari file eksternal.',
                        'Mahasiswa mempelajari Non-blocking I/O melalui Async/Await, Fetch API, dan strategi Hydration data ke LocalStorage.',
                        '---',
                        '### Mengapa JavaScript Butuh \'Asynchronous\'?',
                        'card:JavaScript adalah Single-Thread:JS hanya bisa menjalankan satu tugas sekaligus. Tanpa async, mengambil data dari file/API akan membekukan seluruh halaman sampai data selesai diunduh. Bayangkan toko yang menutup pintunya saat kasir sedang menelepon.',
                        'card:Async/Await: Syntax yang Manusiawi:Async/await bukan fitur baru — ia adalah sintaks yang membuat kode asynchronous terlihat seperti kode synchronous biasa. Lebih mudah dibaca, lebih mudah debug, dan sudah menjadi standar industri.',
                        'card:Pola Hydration: Fetch Sekali, Simpan Selamanya:Kita tidak fetch data.json setiap kali halaman dibuka — hanya saat LocalStorage kosong. Setelah data ada di storage, tidak perlu fetch lagi. Ini strategi yang sama digunakan PWA modern.',
                        '---',
                        '### Sync vs Async — Analogi yang Jelas',
                        '```javascript',

                        'code:js:dracula:true:// ===== SYNCHRONOUS — Blokir sampai selesai =====\n// Seperti antri di kasir: tidak bisa ngobrol sampai giliran selesai\nconsole.log(\'1. Mulai\');\nconst data = fetchDataSync(); // Membekukan browser sampai data datang!\nconsole.log(\'2. Data:\', data);\nconsole.log(\'3. Selesai\');\n// Output: 1 → (browser beku) → 2 → 3\n\n// ===== ASYNCHRONOUS dengan Async/Await =====\n// Seperti pesan makanan online: Anda bisa ngobrol sambil menunggu\nasync function loadData() {\n  console.log(\'1. Mulai muat data...\');\n  try {\n    const response = await fetch(\'./data.json\'); // Tunggu tanpa membekukan\n    const data     = await response.json();      // Parse JSON-nya\n    console.log(\'3. Data diterima:\', data);\n  } catch (error) {\n    console.error(\'Gagal memuat data:\', error.message);\n  }\n}\n\nconsole.log(\'2. Baris ini jalan TANPA menunggu fetch!\');\nloadData();\n// Output: 1 → 2 → (menunggu di background) → 3',
                        '```',
                        '---',
                        '### Strategi Hydration — Implementasi Lengkap',
                        '```javascript',

                        'code:js:nord:true:// ===== POLA HYDRATION YANG BENAR =====\n// Prinsip: Fetch hanya jika LocalStorage kosong\n\nasync function initApp() {\n  const stored = localStorage.getItem(STORAGE_KEY);\n\n  if (stored) {\n    // Data sudah ada di LocalStorage — langsung pakai\n    articles = JSON.parse(stored);\n    console.log(`Memuat ${articles.length} artikel dari LocalStorage`);\n  } else {\n    // LocalStorage kosong — fetch data awal dari file JSON\n    console.log(\'LocalStorage kosong. Fetching data.json...\');\n    try {\n      const response = await fetch(\'./data.json\');\n\n      if (!response.ok) {\n        throw new Error(`HTTP Error: ${response.status}`);\n      }\n\n      articles = await response.json();\n\n      // Simpan ke LocalStorage agar tidak perlu fetch lagi\n      saveToStorage();\n      console.log(`${articles.length} artikel berhasil dimuat dan disimpan.`);\n\n    } catch (err) {\n      console.error(\'Gagal fetch data.json:\', err.message);\n      articles = []; // Fallback: mulai kosong\n    }\n  }\n\n  renderTable(); // Render setelah data siap\n}\n\n// Ganti: let articles = loadFromStorage(); renderTable();\n// Dengan:\ninitApp(); // Panggil di akhir file',
                        '```',
                        '---',
                        '### Struktur data.json yang Benar',
                        '```javascript',

                        'code:json:github-dark:true:[\n  {\n    "id": 1706000001000,\n    "title": "Pengenalan HTML5 Semantik",\n    "content": "HTML5 membawa tag semantik yang membantu browser dan developer memahami struktur halaman dengan lebih baik.",\n    "createdAt": "23/03/2026"\n  },\n  {\n    "id": 1706000002000,\n    "title": "CSS Flexbox untuk Layout Modern",\n    "content": "Flexbox adalah model layout CSS yang memudahkan pembuatan antarmuka responsif tanpa hack float.",\n    "createdAt": "23/03/2026"\n  },\n  {\n    "id": 1706000003000,\n    "title": "Vanilla JavaScript DOM Manipulation",\n    "content": "Manipulasi DOM adalah cara JavaScript berinteraksi dengan elemen HTML di halaman secara dinamis.",\n    "createdAt": "23/03/2026"\n  }\n]',
                        '```',
                        '---',
                        '### 3 Konsep Asynchronous',
                        'card:async/await:Tambahkan async sebelum function dan await sebelum operasi yang butuh waktu. await hanya bisa digunakan di dalam fungsi async.',
                        'card:Fetch API:fetch(url) mengirim HTTP request dan mengembalikan Promise. .json() adalah method response yang juga async — butuh await juga.',
                        'card:Try-Catch:Bungkus kode async dalam try-catch untuk menangkap error jaringan. Tanpa ini, error yang tidak tertangkap bisa crash seluruh aplikasi tanpa pesan yang jelas.',
                        '---',
                        '### Alur Integrasi Data',
                        'skill:100%:Buat data.json dengan minimal 3 artikel dummy:Step 1 — Data Source',
                        'skill:85%:Implementasikan initApp() dengan pola hydration:Step 2 — Core Logic',
                        'skill:90%:Test: clear storage → refresh → data muncul dari fetch:Step 3 — Validasi',
                        'skill:85%:Test: refresh tanpa clear → data dari storage (tidak fetch):Step 4 — Efisiensi',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Buat data.json", "Deskripsi Tugas": "Buat file data.json dengan 5 artikel dummy. Validasi JSON di jsonlint.com sebelum digunakan."}, {"Aktivitas": "Fungsi initApp()", "Deskripsi Tugas": "Implementasikan pola hydration: cek storage → jika kosong fetch → simpan → render."}, {"Aktivitas": "Test Hydration", "Deskripsi Tugas": "Clear LocalStorage via DevTools, refresh halaman. Konfirmasi data muncul dari data.json. Refresh lagi — sekarang dari storage."}, {"Aktivitas": "Error Handling", "Deskripsi Tugas": "Ganti URL fetch dengan URL salah. Konfirmasi try-catch menampilkan pesan error di console tanpa crash aplikasi."}]',
                        '---'
                    ]
                },
                {
                    id: 'modul12',
                    title: 'Pertemuan 12: CRUD — Create & Read',
                    lines: [
                        '**Pertemuan 12: Implementasi CRUD — Create & Read**',
                        '*Ini bukan sekedar latihan — ini arsitektur aplikasi yang sesungguhnya.*',
                        '---',
                        'Penyatuan seluruh teknologi: HTML Form + DOM + JSON + LocalStorage + Fetch API.',
                        'Fokus pada siklus hidup data lengkap dari pengambilan awal (Read) hingga penambahan data baru (Create) yang tersimpan permanen.',
                        '---',
                        '### Perbedaan dengan Pertemuan 6 (Array Sementara)',
                        'card:Dulu: Array di Memori:Di P6, data disimpan di array yang hilang saat refresh. Itu prototype. Sekarang array tetap, tapi selalu disinkronkan dengan LocalStorage — data tidak pernah hilang.',
                        'card:Sekarang: 3 Lapisan Data:Layer 1: Array JavaScript (cepat, di memori). Layer 2: LocalStorage (permanen, di browser). Layer 3: data.json (sumber data awal, di server/file). Ketiganya bekerja bersama.',
                        'card:Aturan Besi: Satu Source of Truth:Array JavaScript adalah satu-satunya sumber kebenaran. Storage dibaca sekali saat startup, ditulis setiap ada perubahan. Tampilan selalu dirender dari array — tidak pernah dari DOM langsung.',
                        '---',
                        '### Arsitektur Lengkap app.js (Create + Read)',
                        '```javascript',

                        'code:js:dracula:true:// ============================================================\n// app.js — Article System v2 (dengan LocalStorage + Fetch)\n// ============================================================\n\n// === 1. KONSTANTA ===\nconst STORAGE_KEY = \'niura_articles\';\n\n// === 2. DOM ELEMENTS ===\nconst articleForm  = document.getElementById(\'articleForm\');\nconst inputTitle   = document.getElementById(\'inputTitle\');\nconst inputContent = document.getElementById(\'inputContent\');\nconst tableBody    = document.getElementById(\'tableBody\');\nconst toastNotif   = document.getElementById(\'toastNotif\');\n\n// === 3. STATE ===\nlet articles = [];\n\n// === 4. STORAGE HELPERS ===\nfunction saveToStorage() {\n  localStorage.setItem(STORAGE_KEY, JSON.stringify(articles));\n}\n\n// === 5. RENDER ===\nfunction renderTable(data = articles) {\n  tableBody.innerHTML = \'\';\n  if (data.length === 0) {\n    tableBody.innerHTML = \'<tr><td colspan="5" class="empty-state">Belum ada artikel.</td></tr>\';\n    return;\n  }\n  data.forEach((a, i) => {\n    const tr = document.createElement(\'tr\');\n    tr.innerHTML = `\n      <td>${i + 1}</td>\n      <td>${escapeHTML(a.title)}</td>\n      <td>${escapeHTML(a.content).substring(0, 80)}...</td>\n      <td>${a.createdAt || \'-\'}</td>\n      <td class="actions">\n        <button class="btn-primary" onclick="setupEdit(${a.id})">Edit</button>\n        <button class="btn-danger"  onclick="deleteArticle(${a.id})">Hapus</button>\n      </td>`;\n    tableBody.appendChild(tr);\n  });\n}\n\n// Escape HTML untuk mencegah XSS\nfunction escapeHTML(str) {\n  const div = document.createElement(\'div\');\n  div.textContent = str;\n  return div.innerHTML;\n}\n\n// === 6. UTILITIES ===\nfunction clearForm() { inputTitle.value = \'\'; inputContent.value = \'\'; inputTitle.focus(); }\nfunction showToast(msg, type = \'success\') {\n  toastNotif.textContent = msg;\n  toastNotif.className = `toast ${type} show`;\n  setTimeout(() => toastNotif.classList.remove(\'show\'), 2500);\n}\n\n// === 7. CREATE ===\narticleForm.addEventListener(\'submit\', e => {\n  e.preventDefault();\n  const title   = inputTitle.value.trim();\n  const content = inputContent.value.trim();\n  if (!title)   { showToast(\'Judul wajib diisi!\', \'error\'); return; }\n  if (!content) { showToast(\'Konten wajib diisi!\', \'error\'); return; }\n\n  articles.push({\n    id: Date.now(), title, content,\n    createdAt: new Date().toLocaleDateString(\'id-ID\')\n  });\n  saveToStorage();\n  renderTable();\n  clearForm();\n  showToast(\'Artikel berhasil disimpan!\');\n});\n\n// === 8. INIT (Fetch + Hydration) ===\nasync function initApp() {\n  const stored = localStorage.getItem(STORAGE_KEY);\n  if (stored) {\n    articles = JSON.parse(stored);\n  } else {\n    try {\n      const res = await fetch(\'./data.json\');\n      articles  = await res.json();\n      saveToStorage();\n    } catch (e) {\n      articles = [];\n    }\n  }\n  renderTable();\n}\n\ninitApp();',
                        '```',
                        '---',
                        '### Target Fungsionalitas',
                        'skill:100%:initApp() dengan pola hydration berjalan:Kunci Aplikasi',
                        'skill:95%:Form submit → push → saveToStorage → renderTable:Alur Create',
                        'skill:80%:Fungsi escapeHTML() mencegah XSS injection:Security Dasar',
                        'skill:100%:Test alur: tambah → refresh → data masih ada:Bukti Berhasil',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Integrasi initApp", "Deskripsi Tugas": "Ganti inisialisasi lama dengan initApp(). Test: clear storage, refresh, konfirmasi data dari data.json muncul."}, {"Aktivitas": "Uji Create", "Deskripsi Tugas": "Tambah 3 artikel baru. Buka DevTools Application → LocalStorage. Konfirmasi data tersimpan sebagai JSON."}, {"Aktivitas": "Uji Persistence", "Deskripsi Tugas": "Tambah artikel, tutup tab, buka kembali URL yang sama. Data harus tetap ada."}, {"Aktivitas": "Uji Security", "Deskripsi Tugas": "Input judul: &lt;img src=x onerror=alert(1)&gt;. Konfirmasi teks ditampilkan literal — bukan dieksekusi sebagai HTML."}]',
                        '---'
                    ]
                }
            ]
        },
        {
            name: 'Bagian 4: CRUD Penuh & Finalisasi',
            items: [
                {
                    id: 'modul13',
                    title: 'Pertemuan 13: CRUD — Update & Delete',
                    lines: [
                        '**Pertemuan 13: Implementasi CRUD — Update & Delete**',
                        '*Aplikasi yang tidak bisa mengedit dan menghapus data bukan aplikasi — itu hanya form.*',
                        '---',
                        'Tahap penyelesaian siklus CRUD penuh. Mahasiswa mempelajari manipulasi data spesifik via ID unik, Event Delegation, dan pengelolaan editing state untuk fitur Update dan Delete yang robust.',
                        '---',
                        '### Dua Tantangan Utama Update & Delete',
                        'card:Delete: Mudah tapi Berbahaya:Delete mudah secara kode (.filter()), tapi berbahaya UX-nya tanpa konfirmasi. Hapus tanpa konfirmasi membuat pengguna tidak bisa kembali. Gunakan modal konfirmasi — bukan window.confirm() bawaan browser.',
                        'card:Update: Butuh State Management:Update membutuhkan sistem untuk \'mengingat\' artikel mana yang sedang diedit. Solusinya: simpan ID di hidden input saat modal dibuka, gunakan ID itu untuk menemukan dan memperbarui data.',
                        'card:Event Delegation untuk Tombol Dinamis:Tombol Edit dan Hapus dibuat oleh JavaScript secara dinamis — tidak bisa langsung ditambahkan event listener. Pola onclick inline (onclick=\'deleteArticle(id)\') adalah solusi paling sederhana untuk skala proyek ini.',
                        '---',
                        '### Implementasi Update — setupEdit() & updateArticle()',
                        '```javascript',

                        'code:js:dracula:true:// DOM tambahan yang dibutuhkan untuk modal edit\nconst modalOverlay = document.getElementById(\'modalOverlay\');\nconst editId       = document.getElementById(\'editId\');       // hidden input\nconst editTitle    = document.getElementById(\'editTitle\');\nconst editContent  = document.getElementById(\'editContent\');\nconst btnUpdate    = document.getElementById(\'btnUpdate\');\nconst btnClose     = document.getElementById(\'btnCloseModal\');\n\n// ===== BUKA MODAL DAN ISI DATA =====\nfunction setupEdit(id) {\n  // Cari artikel berdasarkan ID\n  const article = articles.find(a => a.id === id);\n  if (!article) return;\n\n  // Isi form modal dengan data yang ada\n  editId.value      = article.id;       // Simpan ID di hidden input\n  editTitle.value   = article.title;\n  editContent.value = article.content;\n\n  openModal();\n  editTitle.focus(); // Fokus ke field pertama\n}\n\n// ===== SIMPAN PERUBAHAN =====\nbtnUpdate.addEventListener(\'click\', function() {\n  const id      = Number(editId.value); // Konversi kembali ke number!\n  const title   = editTitle.value.trim();\n  const content = editContent.value.trim();\n\n  if (!title || !content) {\n    showToast(\'Judul dan konten wajib diisi!\', \'error\');\n    return;\n  }\n\n  // Cari index artikel yang akan diupdate\n  const index = articles.findIndex(a => a.id === id);\n  if (index !== -1) {\n    articles[index].title   = title;    // Perbarui properti\n    articles[index].content = content;\n    articles[index].updatedAt = new Date().toLocaleDateString(\'id-ID\');\n  }\n\n  saveToStorage(); // Simpan perubahan\n  renderTable();\n  closeModal();\n  showToast(\'Artikel berhasil diperbarui!\');\n});\n\n// ===== TUTUP MODAL =====\nfunction openModal()  { modalOverlay.classList.add(\'active\');    }\nfunction closeModal() { modalOverlay.classList.remove(\'active\'); }\nbtnClose.addEventListener(\'click\', closeModal);\nmodalOverlay.addEventListener(\'click\', e => {\n  if (e.target === modalOverlay) closeModal(); // Klik overlay untuk tutup\n});',
                        '```',
                        '---',
                        '### Implementasi Delete — dengan Modal Konfirmasi',
                        '```javascript',

                        'code:js:nord:true:// ===== DELETE SEDERHANA (tanpa konfirmasi) =====\nfunction deleteArticle(id) {\n  articles = articles.filter(a => a.id !== id);\n  saveToStorage();\n  renderTable();\n  showToast(\'Artikel dihapus!\');\n}\n\n// ===== DELETE DENGAN KONFIRMASI MODAL (lebih baik) =====\nlet pendingDeleteId = null; // State untuk menyimpan ID yang akan dihapus\n\nfunction confirmDelete(id) {\n  pendingDeleteId = id;\n  openConfirmModal(); // Buka modal konfirmasi terpisah\n}\n\n// Di modal konfirmasi:\nfunction executeDelete() {\n  if (!pendingDeleteId) return;\n\n  articles = articles.filter(a => a.id !== pendingDeleteId);\n  saveToStorage();\n  renderTable();\n  closeConfirmModal();\n  showToast(\'Artikel berhasil dihapus!\');\n\n  pendingDeleteId = null; // Reset state\n}\n\n// ===== UPDATE renderTable() — Ganti tombol hapus =====\n// Ganti: onclick="deleteArticle(${a.id})"\n// Jadi : onclick="confirmDelete(${a.id})"  ← lebih aman\n\n// ⚠️ PENTING: editId.value menyimpan ID sebagai STRING\n// Saat dipakai, konversi ke number dengan Number() atau parseInt()\n// const id = Number(editId.value); // Bukan editId.value langsung!',
                        '```',
                        '---',
                        '### 3 Pilar Manipulasi Data',
                        'card:Targeting by ID:.find(a => a.id === id) mencari satu item. .findIndex() mencari posisinya. ID disimpan di hidden input (editId) selama modal terbuka — ini \'ingatan\' state management kita.',
                        'card:Data Filtering untuk Delete:.filter() membuat array baru tanpa item yang ID-nya cocok. Lebih aman dari splice() karena tidak memodifikasi array asli secara langsung.',
                        'card:Editing State via Hidden Input:<input type=\'hidden\' id=\'editId\'> menyimpan ID artikel yang sedang diedit. JavaScript tidak butuh variabel global tambahan — state tersimpan di DOM itu sendiri.',
                        '---',
                        '### Kompetensi Manipulasi Data',
                        'skill:85%:setupEdit(): populate modal form dari .find():Core Update Logic',
                        'skill:85%:updateArticle(): modifikasi array via findIndex():Complex tapi Kritis',
                        'skill:80%:Modal konfirmasi delete tanpa window.confirm():UX Modern',
                        'skill:90%:Number(editId.value) untuk konversi tipe data:Bug Prevention',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "setupEdit()", "Deskripsi Tugas": "Implementasikan fungsi yang mengisi form modal dari artikel yang dipilih. Test klik Edit pada setiap baris."}, {"Aktivitas": "updateArticle()", "Deskripsi Tugas": "Implementasikan handler btnUpdate: ambil editId, cari dengan findIndex, update properti, save, render."}, {"Aktivitas": "Konfirmasi Delete", "Deskripsi Tugas": "Buat modal konfirmasi sederhana dengan tombol \'Ya, Hapus\' dan \'Batal\'. Ganti deleteArticle langsung."}, {"Aktivitas": "Full CRUD Test", "Deskripsi Tugas": "Test alur lengkap: tambah → read → edit → simpan → hapus → konfirmasi → refresh. Semua harus berjalan tanpa error."}]',
                        '---'
                    ]
                },
                {
                    id: 'modul14',
                    title: 'Pertemuan 14: Integrasi Proyek & Finalisasi',
                    lines: [
                        '**Pertemuan 14: Integrasi Proyek & Finalisasi Modul Niura**',
                        '*Kode yang bekerja adalah versi 1.0. Kode yang bersih, terstruktur, dan terarah adalah versi profesional.*',
                        '---',
                        'Fase finalisasi teknis sebelum presentasi. Fokus pada search real-time, refactoring, branding Niura, dan pengujian menyeluruh — karena kualitas produk diuji dari detailnya.',
                        '---',
                        '### Tiga Hal yang Membedakan Proyek Biasa dari Proyek Berkesan',
                        'card:Search Real-Time:Sebuah tabel dengan 20 baris tanpa fitur cari adalah UX yang buruk. Fitur search menggunakan .filter() yang sudah dikuasai — hanya butuh event listener pada input dan renderTable dengan data terfilter.',
                        'card:Refactoring = Profesionalisme:Hapus semua console.log yang tidak perlu, pastikan tidak ada variabel yang tidak digunakan, dan berikan komentar bermakna. Penilai membaca kode Anda — pastikan ia berbicara sendiri.',
                        'card:Konsistensi Branding:CSS Variables di :root sudah menjadi design system. Pastikan semua tombol, warna, dan tipografi konsisten. Satu warna yang tidak sesuai tema lebih mengganggu dari satu bug minor.',
                        '---',
                        '### Implementasi Search Real-Time',
                        '```javascript',

                        'code:js:dracula:true:// HTML yang dibutuhkan: tambahkan di atas tabel\n// <input type="search" id="searchInput" placeholder="Cari artikel...">\n\nconst searchInput = document.getElementById(\'searchInput\');\n\n// Event: jalankan setiap karakter yang diketik\nsearchInput.addEventListener(\'input\', function() {\n  const keyword = this.value.trim().toLowerCase();\n  searchArticles(keyword);\n});\n\nfunction searchArticles(keyword) {\n  if (!keyword) {\n    renderTable(articles); // Kosong = tampilkan semua\n    return;\n  }\n\n  const results = articles.filter(a =>\n    a.title.toLowerCase().includes(keyword) ||\n    a.content.toLowerCase().includes(keyword)\n  );\n\n  renderTable(results); // renderTable sudah menerima parameter data\n\n  // Feedback jumlah hasil\n  if (results.length === 0) {\n    tableBody.innerHTML = `\n      <tr><td colspan="5" class="empty-state">\n        Tidak ada artikel yang cocok dengan "${keyword}".\n      </td></tr>\n    `;\n  }\n}\n\n// ⚠️ Pastikan renderTable() menerima parameter:\n// function renderTable(data = articles) { ... }\n//                      ↑ Default ke articles jika tidak ada argumen',
                        '```',
                        '---',
                        '### Checklist Final Kualitas Kode',
                        '```javascript',

                        'code:js:monokai:false:// ✅ CHECKLIST FINAL SEBELUM DEMO\n\n// === JAVASCRIPT ===\n// ✅ Tidak ada console.log yang tertinggal (kecuali sengaja)\n// ✅ Semua fungsi memiliki komentar singkat\n// ✅ Tidak ada variabel yang dideklarasikan tapi tidak dipakai\n// ✅ Semua operasi CRUD selalu diikuti saveToStorage()\n// ✅ preventDefault() ada di semua form submit handler\n// ✅ editId.value dikonversi dengan Number() sebelum dipakai\n// ✅ escapeHTML() digunakan untuk semua output ke innerHTML\n\n// === HTML ===\n// ✅ Semua ID unik dan konsisten dengan JS\n// ✅ Tag semantik digunakan dengan tepat\n// ✅ Meta viewport ada di <head>\n// ✅ <script> di bagian paling bawah <body>\n\n// === CSS ===\n// ✅ CSS Variables terdefinisi di :root\n// ✅ Media query minimal untuk 640px\n// ✅ Tidak ada nilai warna hardcoded di luar :root\n// ✅ Transisi modal dan toast berjalan mulus\n\n// === UX ===\n// ✅ Empty state ditampilkan saat data kosong\n// ✅ Toast notification muncul setelah setiap aksi\n// ✅ Search real-time berfungsi tanpa reload\n// ✅ Modal menutup saat klik overlay\n// ✅ Form ter-clear dan fokus kembali setelah submit',
                        '```',
                        '---',
                        '### Kesiapan Produksi',
                        'skill:100%:Search real-time berfungsi di semua field:Feature Complete',
                        'skill:95%:Refactoring: komentar + hapus console.log:Code Quality',
                        'skill:95%:Test responsivitas di mobile (DevTools):Mobile Ready',
                        'skill:100%:Semua alur CRUD tanpa error di console:Bug Free',
                        '---',
                        '### Aktivitas Praktikum Final Polish',
                        'table:[{"Aktivitas": "Search Logic", "Deskripsi Tugas": "Implementasikan fungsi searchArticles(). Tambahkan input search di HTML. Test dengan keyword yang ada dan yang tidak ada."}, {"Aktivitas": "Branding Sync", "Deskripsi Tugas": "Verifikasi semua warna menggunakan CSS Variables. Tidak ada hex color hardcoded di luar :root."}, {"Aktivitas": "Code Refactoring", "Deskripsi Tugas": "Hapus semua console.log debug. Tambahkan komentar section di app.js. Verifikasi tidak ada dead code."}, {"Aktivitas": "Final Flow Test", "Deskripsi Tugas": "Jalankan skenario: Clear storage → Fetch data → Add → Search → Edit → Delete → Refresh → Verifikasi."}]',
                        '---'
                    ]
                },
                {
                    id: 'modul15',
                    title: 'Pertemuan 15: Final Review & Demo Project',
                    lines: [
                        '**Pertemuan 15: Final Review & Demo Project \'Article System\'**',
                        '*Satu semester perjalanan teknis — sekarang waktunya membuktikannya.*',
                        '---',
                        'Mahasiswa melakukan pengujian akhir (QA), demonstrasi fitur secara langsung, dan pembuktian persistensi data Article System yang telah dibangun selama satu semester.',
                        '---',
                        '### Apa yang Harus Bisa Anda Demonstrasikan?',
                        'card:Persistensi yang Nyata:Demonstrasikan: tambah artikel → tutup browser → buka kembali → data masih ada. Ini satu momen yang membuktikan LocalStorage berjalan. Penonton yang terkesan adalah penilai yang puas.',
                        'card:Jelaskan Logikanya, Bukan Hanya Kliknya:Penilai ingin tahu apakah Anda paham kode Anda sendiri. Saat demo, jelaskan: \'Ini saveToStorage() yang sinkronkan array ke LocalStorage setiap kali ada perubahan.\' Bukan hanya: \'Ini tombol simpan.\'',
                        'card:Tunjukkan DevTools:Buka Application → LocalStorage saat demo. Tunjukkan bahwa data tersimpan sebagai JSON. Ini bukti teknis yang membedakan developer yang paham dari developer yang hanya copy-paste.',
                        '---',
                        '### Rubrik Penilaian Final',
                        'table:[{"Komponen": "Kualitas CRUD", "Bobot": "40%", "Indikator": "Fungsi C-R-U-D berjalan 100% tanpa error di console. Search real-time berfungsi."}, {"Komponen": "Integrasi Data", "Bobot": "20%", "Indikator": "Fetch API + LocalStorage + Hydration berjalan sesuai pola yang diajarkan."}, {"Komponen": "User Experience", "Bobot": "20%", "Indikator": "Responsif di mobile, toast notification, modal edit, empty state, konfirmasi hapus."}, {"Komponen": "Visual Branding", "Bobot": "10%", "Indikator": "CSS Variables konsisten, tipografi rapi, warna Niura seragam."}, {"Komponen": "Presentasi", "Bobot": "10%", "Indikator": "Mampu menjelaskan fungsi-fungsi kunci: renderTable, saveToStorage, initApp, setupEdit."}]',
                        '---',
                        '### Kilas Balik Perjalanan Semester',
                        'card:P1–P4: Foundation:Dari HTML boilerplate kosong hingga antarmuka dengan modal dan toast yang beranimasi. 4 pertemuan untuk membangun UI yang benar-benar siap disambungkan ke logika.',
                        'card:P5–P8: JavaScript Logic:DOM selection, event listeners, renderTable(), add, delete, validasi — semua fondasi logika CRUD tanpa penyimpanan permanen. Diuji di UTS.',
                        'card:P9–P14: Data & Integration:JSON, LocalStorage, Fetch API, Update, Delete dengan konfirmasi, search real-time, refactoring. Dari aplikasi sementara menjadi aplikasi yang benar-benar berfungsi.',
                        '---',
                        '### Kriteria Kelulusan Proyek',
                        'skill:100%:Full CRUD: Create, Read, Update, Delete:Wajib',
                        'skill:100%:Persistensi LocalStorage + Fetch Hydration:Wajib',
                        'skill:90%:Responsivitas UI/UX di mobile:Stabil',
                        'skill:85%:Mampu jelaskan kode saat presentasi:Komprehensif',
                        '---'
                    ]
                },
                {
                    id: 'modul16',
                    title: 'UAS: Pengembangan SPA — CMS',
                    lines: [
                        '**UAS: Pengembangan Single Page Application (SPA) — CMS**',
                        '*Ini bukan tentang menyelesaikan ujian — ini tentang membuktikan Anda seorang web developer.*',
                        '---',
                        'UAS menguji kemampuan integrasi menyeluruh: arsitektur SPA, manajemen state JavaScript, dan persistensi data LocalStorage.',
                        'Anda ditantang membangun CMS fungsional dari nol dengan standar yang sama digunakan di industri.',
                        '---',
                        '### Apa yang Membuat UAS Ini Berbeda dari UTS?',
                        'card:SPA: Navigasi Tanpa Reload:UTS hanya butuh satu halaman. UAS butuh navigasi antar \'halaman\' (Dashboard, List, Add/Edit) tanpa reload. Ini adalah arsitektur Single Page Application — cara semua web app modern bekerja.',
                        'card:Full CRUD vs C+D saja:UTS menguji Create dan Delete (dan render). UAS menguji seluruh siklus CRUD termasuk Update — operasi paling kompleks karena membutuhkan state management dan form population.',
                        'card:Data Hydration via Fetch:UTS hanya punya array sementara. UAS mengintegrasikan Fetch API dengan LocalStorage dalam pola hydration yang benar — data tetap ada bahkan jika storage dihapus manual.',
                        '---',
                        '### Arsitektur SPA — Navigasi Tanpa Reload',
                        '```javascript',

                        'code:js:dracula:true:// ===== POLA SPA NAVIGATION =====\n// Setiap \'halaman\' sebenarnya adalah section yang disembunyikan/ditampilkan\n\n// HTML yang dibutuhkan:\n// <nav>\n//   <a href="#" onclick="navigate(\'dashboard\')">Dashboard</a>\n//   <a href="#" onclick="navigate(\'list\')">Daftar Artikel</a>\n//   <a href="#" onclick="navigate(\'add\')">Tambah Artikel</a>\n// </nav>\n// <section id="page-dashboard" class="page">...</section>\n// <section id="page-list"      class="page">...</section>\n// <section id="page-add"       class="page">...</section>\n\n// CSS:\n// .page { display: none; }\n// .page.active { display: block; }\n\n// JavaScript:\nfunction navigate(pageName) {\n  // Sembunyikan semua halaman\n  document.querySelectorAll(\'.page\').forEach(p => p.classList.remove(\'active\'));\n\n  // Tampilkan halaman yang dituju\n  const target = document.getElementById(`page-${pageName}`);\n  if (target) target.classList.add(\'active\');\n\n  // Update navigasi aktif\n  document.querySelectorAll(\'nav a\').forEach(a => a.classList.remove(\'nav-active\'));\n  document.querySelector(`[onclick*="\'${pageName}\'"]`)?.classList.add(\'nav-active\');\n\n  // Refresh data saat masuk halaman list\n  if (pageName === \'list\') renderTable();\n  if (pageName === \'dashboard\') updateDashboardStats();\n}\n\n// Tampilkan halaman pertama saat load\nnavigate(\'dashboard\');',
                        '```',
                        '---',
                        '### Dashboard Stats — Fitur Bonus yang Berkesan',
                        '```javascript',

                        'code:js:nord:true:// Fungsi untuk menampilkan statistik ringkasan di Dashboard\nfunction updateDashboardStats() {\n  const total   = articles.length;\n  const thisMonth = articles.filter(a => {\n    const date = new Date(a.createdAt.split(\'/\').reverse().join(\'-\'));\n    const now  = new Date();\n    return date.getMonth() === now.getMonth() &&\n           date.getFullYear() === now.getFullYear();\n  }).length;\n\n  // Update elemen stat di Dashboard\n  const elTotal = document.getElementById(\'statTotal\');\n  const elMonth = document.getElementById(\'statThisMonth\');\n\n  if (elTotal) elTotal.textContent = total;\n  if (elMonth) elMonth.textContent = thisMonth;\n}\n\n// HTML Dashboard contoh:\n// <div class="stat-card">\n//   <span id="statTotal" class="stat-number">0</span>\n//   <span class="stat-label">Total Artikel</span>\n// </div>\n// <div class="stat-card">\n//   <span id="statThisMonth" class="stat-number">0</span>\n//   <span class="stat-label">Bulan Ini</span>\n// </div>',
                        '```',
                        '---',
                        '### Rubrik Penilaian UAS (100%)',
                        'table:[{"No": "1", "Kriteria": "Logika CRUD Penuh", "Bobot": "30%", "Deskripsi": "C-R-U-D berjalan sempurna: tambah, tampil, edit, simpan perubahan, hapus dengan konfirmasi."}, {"No": "2", "Kriteria": "Arsitektur SPA", "Bobot": "20%", "Deskripsi": "Navigasi antar menu (min 3: Dashboard/List/Add) tanpa reload. preventDefault() pada semua link/form."}, {"No": "3", "Kriteria": "Persistensi Data", "Bobot": "20%", "Deskripsi": "LocalStorage berfungsi. Fetch + Hydration: data muncul dari data.json jika storage kosong."}, {"No": "4", "Kriteria": "UI/UX & Responsivitas", "Bobot": "20%", "Deskripsi": "Desain profesional, rapi di mobile, CSS Variables Niura, toast, empty state, loading state."}, {"No": "5", "Kriteria": "Kualitas Kode", "Bobot": "10%", "Deskripsi": "Kode modular, komentar pada setiap fungsi, tidak ada console.log debug, struktur folder rapi."}]',
                        '---',
                        '### Target Kualitas Aplikasi',
                        'skill:100%:Logika JavaScript ES6+ yang bersih dan modular:Advanced',
                        'skill:90%:UI/UX responsif dengan CSS Variables Niura:Polished',
                        'skill:85%:SPA navigation minimal 3 menu tanpa reload:Architectural',
                        'skill:85%:Dokumentasi kode: komentar dan penamaan deskriptif:Professional',
                        '---',
                        '### Tips Terakhir untuk Sukses UAS',
                        'card:Kerjakan Bertahap, Bukan Sekaligus:Mulai dari HTML + navigasi SPA → CSS → CRUD dasar (tanpa storage) → tambah storage → tambah fetch → polish UI. Jangan loncat ke Fetch sebelum CRUD dasar berjalan.',
                        'card:Console adalah GPS Anda:Setiap error di Console memiliki nomor baris. Baca pesannya, buka file di baris itu, perbaiki. Jangan panik melihat error merah — itu informasi, bukan hukuman.',
                        'card:Kode yang Bekerja > Kode yang Cantik:Jika waktu terbatas, prioritaskan fungsionalitas (70% nilai) baru visual (20% nilai). CMS yang fungsional tapi tampilan sederhana lebih bernilai dari CMS cantik yang CRUD-nya tidak jalan.',
                        '---'
                    ]
                }
            ]
        }
    ]
};
